export type CheckoutIconNames =
  | 'arrowDown'
  | 'calendar'
  | 'check'
  | 'creditCard'
  | 'cvv'
  | 'dollar'
  | 'lock'
  | 'spinner'
  | 'user'
  | 'warning'
  | 'poweredByPlug'
  | 'edit'
  | 'eye'
  | 'eyeSlash'
  | 'arrowLeft'
  | 'error'
  | 'checkLarge'
  | 'clipboard'
  | 'pix'
  | 'newTab'

export type CheckoutIconsObject = Record<CheckoutIconNames, string>
