export type CheckoutIconNames =
  | 'arrowDown'
  | 'calendar'
  | 'check'
  | 'creditCard'
  | 'cvv'
  | 'dollar'
  | 'lock'
  | 'spinner'
  | 'user'
  | 'warning'
  | 'poweredByMalga'
  | 'edit'
  | 'eye'
  | 'eyeSlash'
  | 'arrowLeft'
  | 'error'
  | 'checkLarge'
  | 'clipboard'
  | 'pix'
  | 'newTab'
  | 'american-express'
  | 'diners-club'
  | 'discover'
  | 'elo'
  | 'hipercard'
  | 'mastercard'
  | 'visa'
  | 'globe'
  | 'nubank'
  | 'drip'
  | 'close'

export type CheckoutIconsObject = Record<CheckoutIconNames, string>
