blank_issues_enabled: false
contact_links:
  - name: 🤔 Support/Usage Question
    url: https://discord.com/h5J5ZkhTXV
    about: This is a bug tracker, not a support system. For usage questions, please use Dicord where there are a lot more people ready to help you out. Thanks!
