/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Locale } from "@malga-checkout/i18n/dist/utils";
import { MalgaAppInfo, MalgaCheckoutFullChargeError, MalgaCheckoutFullChargeSuccess, MalgaCheckoutFullDialog, MalgaCheckoutFullPage, MalgaCheckoutFullPaymentMethods, MalgaCheckoutFullTransaction } from "./components/malga-checkout-full/malga-checkout-full.types";
import { MalgaCheckoutFullIdentificationFormValues } from "./components/malga-checkout-full/partials/malga-checkout-full-identification/malga-checkout-full-identification.types";
export namespace Components {
    interface MalgaCheckoutFull {
        "appInfo"?: MalgaAppInfo;
        "clientId"?: string;
        "debug": boolean;
        "dialogConfig": MalgaCheckoutFullDialog;
        "idempotencyKey"?: string;
        "locale"?: Locale;
        "merchantId"?: string;
        "pageConfig"?: MalgaCheckoutFullPage;
        "paymentMethods"?: MalgaCheckoutFullPaymentMethods;
        "publicKey"?: string;
        "sandbox": boolean;
        "sessionId"?: string;
        "transactionConfig"?: MalgaCheckoutFullTransaction;
    }
    interface MalgaCheckoutFullContent {
    }
    interface MalgaCheckoutFullFooter {
        "description"?: string;
        "language": string;
    }
    interface MalgaCheckoutFullHeader {
        "backRoute"?: string;
        "brand": string;
        "isLoading": boolean;
        "language": string;
        "locale"?: Locale;
    }
    interface MalgaCheckoutFullIdentification {
        "formValues": MalgaCheckoutFullIdentificationFormValues;
        "internationalCustomer": boolean;
        "isLoading": boolean;
        "locale"?: Locale;
    }
}
declare global {
    interface HTMLMalgaCheckoutFullElement extends Components.MalgaCheckoutFull, HTMLStencilElement {
    }
    var HTMLMalgaCheckoutFullElement: {
        prototype: HTMLMalgaCheckoutFullElement;
        new (): HTMLMalgaCheckoutFullElement;
    };
    interface HTMLMalgaCheckoutFullContentElement extends Components.MalgaCheckoutFullContent, HTMLStencilElement {
    }
    var HTMLMalgaCheckoutFullContentElement: {
        prototype: HTMLMalgaCheckoutFullContentElement;
        new (): HTMLMalgaCheckoutFullContentElement;
    };
    interface HTMLMalgaCheckoutFullFooterElement extends Components.MalgaCheckoutFullFooter, HTMLStencilElement {
    }
    var HTMLMalgaCheckoutFullFooterElement: {
        prototype: HTMLMalgaCheckoutFullFooterElement;
        new (): HTMLMalgaCheckoutFullFooterElement;
    };
    interface HTMLMalgaCheckoutFullHeaderElement extends Components.MalgaCheckoutFullHeader, HTMLStencilElement {
    }
    var HTMLMalgaCheckoutFullHeaderElement: {
        prototype: HTMLMalgaCheckoutFullHeaderElement;
        new (): HTMLMalgaCheckoutFullHeaderElement;
    };
    interface HTMLMalgaCheckoutFullIdentificationElement extends Components.MalgaCheckoutFullIdentification, HTMLStencilElement {
    }
    var HTMLMalgaCheckoutFullIdentificationElement: {
        prototype: HTMLMalgaCheckoutFullIdentificationElement;
        new (): HTMLMalgaCheckoutFullIdentificationElement;
    };
    interface HTMLElementTagNameMap {
        "malga-checkout-full": HTMLMalgaCheckoutFullElement;
        "malga-checkout-full-content": HTMLMalgaCheckoutFullContentElement;
        "malga-checkout-full-footer": HTMLMalgaCheckoutFullFooterElement;
        "malga-checkout-full-header": HTMLMalgaCheckoutFullHeaderElement;
        "malga-checkout-full-identification": HTMLMalgaCheckoutFullIdentificationElement;
    }
}
declare namespace LocalJSX {
    interface MalgaCheckoutFull {
        "appInfo"?: MalgaAppInfo;
        "clientId"?: string;
        "debug"?: boolean;
        "dialogConfig"?: MalgaCheckoutFullDialog;
        "idempotencyKey"?: string;
        "locale"?: Locale;
        "merchantId"?: string;
        "onTransactionFailed"?: (event: CustomEvent<{
    error: MalgaCheckoutFullChargeError
  }>) => void;
        "onTransactionSuccess"?: (event: CustomEvent<{
    data: MalgaCheckoutFullChargeSuccess
  }>) => void;
        "pageConfig"?: MalgaCheckoutFullPage;
        "paymentMethods"?: MalgaCheckoutFullPaymentMethods;
        "publicKey"?: string;
        "sandbox"?: boolean;
        "sessionId"?: string;
        "transactionConfig"?: MalgaCheckoutFullTransaction;
    }
    interface MalgaCheckoutFullContent {
    }
    interface MalgaCheckoutFullFooter {
        "description"?: string;
        "language"?: string;
        "onChangeLanguage"?: (event: CustomEvent<{ value: Locale }>) => void;
    }
    interface MalgaCheckoutFullHeader {
        "backRoute"?: string;
        "brand"?: string;
        "isLoading"?: boolean;
        "language"?: string;
        "locale"?: Locale;
        "onChangeLanguage"?: (event: CustomEvent<{ value: Locale }>) => void;
    }
    interface MalgaCheckoutFullIdentification {
        "formValues"?: MalgaCheckoutFullIdentificationFormValues;
        "internationalCustomer"?: boolean;
        "isLoading"?: boolean;
        "locale"?: Locale;
        "onFieldChange"?: (event: CustomEvent<{ field: string; value: string }>) => void;
        "onManyFieldsChange"?: (event: CustomEvent<{
    customerFormValues: MalgaCheckoutFullIdentificationFormValues
  }>) => void;
        "onSubmitForm"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "malga-checkout-full": MalgaCheckoutFull;
        "malga-checkout-full-content": MalgaCheckoutFullContent;
        "malga-checkout-full-footer": MalgaCheckoutFullFooter;
        "malga-checkout-full-header": MalgaCheckoutFullHeader;
        "malga-checkout-full-identification": MalgaCheckoutFullIdentification;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "malga-checkout-full": LocalJSX.MalgaCheckoutFull & JSXBase.HTMLAttributes<HTMLMalgaCheckoutFullElement>;
            "malga-checkout-full-content": LocalJSX.MalgaCheckoutFullContent & JSXBase.HTMLAttributes<HTMLMalgaCheckoutFullContentElement>;
            "malga-checkout-full-footer": LocalJSX.MalgaCheckoutFullFooter & JSXBase.HTMLAttributes<HTMLMalgaCheckoutFullFooterElement>;
            "malga-checkout-full-header": LocalJSX.MalgaCheckoutFullHeader & JSXBase.HTMLAttributes<HTMLMalgaCheckoutFullHeaderElement>;
            "malga-checkout-full-identification": LocalJSX.MalgaCheckoutFullIdentification & JSXBase.HTMLAttributes<HTMLMalgaCheckoutFullIdentificationElement>;
        }
    }
}
